// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: message/balance_component.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// emit balance
type EmitBalanceByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrencyName  string                 `protobuf:"bytes,3,opt,name=currency_name,json=currencyName,proto3" json:"currency_name,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitBalanceByUserIdRequest) Reset() {
	*x = EmitBalanceByUserIdRequest{}
	mi := &file_message_balance_component_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitBalanceByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitBalanceByUserIdRequest) ProtoMessage() {}

func (x *EmitBalanceByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitBalanceByUserIdRequest.ProtoReflect.Descriptor instead.
func (*EmitBalanceByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{0}
}

func (x *EmitBalanceByUserIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmitBalanceByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmitBalanceByUserIdRequest) GetCurrencyName() string {
	if x != nil {
		return x.CurrencyName
	}
	return ""
}

func (x *EmitBalanceByUserIdRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type EmitBalanceByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       *Balance               `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitBalanceByUserIdResponse) Reset() {
	*x = EmitBalanceByUserIdResponse{}
	mi := &file_message_balance_component_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitBalanceByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitBalanceByUserIdResponse) ProtoMessage() {}

func (x *EmitBalanceByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitBalanceByUserIdResponse.ProtoReflect.Descriptor instead.
func (*EmitBalanceByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{1}
}

func (x *EmitBalanceByUserIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmitBalanceByUserIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmitBalanceByUserIdResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *EmitBalanceByUserIdResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get Balance By User Id
type GetBalanceByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceByUserIdRequest) Reset() {
	*x = GetBalanceByUserIdRequest{}
	mi := &file_message_balance_component_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceByUserIdRequest) ProtoMessage() {}

func (x *GetBalanceByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceByUserIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBalanceByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserBalance   []*Balance             `protobuf:"bytes,3,rep,name=user_balance,json=userBalance,proto3" json:"user_balance,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceByUserIdResponse) Reset() {
	*x = GetBalanceByUserIdResponse{}
	mi := &file_message_balance_component_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceByUserIdResponse) ProtoMessage() {}

func (x *GetBalanceByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceByUserIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBalanceByUserIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceByUserIdResponse) GetUserBalance() []*Balance {
	if x != nil {
		return x.UserBalance
	}
	return nil
}

func (x *GetBalanceByUserIdResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	LockedBalance float64                `protobuf:"fixed64,3,opt,name=locked_balance,json=lockedBalance,proto3" json:"locked_balance,omitempty"`
	UpdatedDate   int64                  `protobuf:"varint,4,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_message_balance_component_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{4}
}

func (x *Balance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Balance) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Balance) GetLockedBalance() float64 {
	if x != nil {
		return x.LockedBalance
	}
	return 0
}

func (x *Balance) GetUpdatedDate() int64 {
	if x != nil {
		return x.UpdatedDate
	}
	return 0
}

// Get All Pair
type GetAllPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPairRequest) Reset() {
	*x = GetAllPairRequest{}
	mi := &file_message_balance_component_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPairRequest) ProtoMessage() {}

func (x *GetAllPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPairRequest.ProtoReflect.Descriptor instead.
func (*GetAllPairRequest) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllPairRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pairs         []string               `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPairResponse) Reset() {
	*x = GetAllPairResponse{}
	mi := &file_message_balance_component_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPairResponse) ProtoMessage() {}

func (x *GetAllPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_balance_component_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPairResponse.ProtoReflect.Descriptor instead.
func (*GetAllPairResponse) Descriptor() ([]byte, []int) {
	return file_message_balance_component_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllPairResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAllPairResponse) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

var File_message_balance_component_proto protoreflect.FileDescriptor

const file_message_balance_component_proto_rawDesc = "" +
	"\n" +
	"\x1fmessage/balance_component.proto\x12\x02bs\x1a\x13message/error.proto\"\x82\x01\n" +
	"\x1aEmitBalanceByUserIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rcurrency_name\x18\x03 \x01(\tR\fcurrencyName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\x91\x01\n" +
	"\x1bEmitBalanceByUserIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\abalance\x18\x03 \x01(\v2\v.bs.BalanceR\abalance\x12\"\n" +
	"\x05error\x18\x04 \x01(\v2\f.error.ErrorR\x05error\"D\n" +
	"\x19GetBalanceByUserIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x99\x01\n" +
	"\x1aGetBalanceByUserIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\fuser_balance\x18\x03 \x03(\v2\v.bs.BalanceR\vuserBalance\x12\"\n" +
	"\x05error\x18\x04 \x01(\v2\f.error.ErrorR\x05error\"\x89\x01\n" +
	"\aBalance\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12%\n" +
	"\x0elocked_balance\x18\x03 \x01(\x01R\rlockedBalance\x12!\n" +
	"\fupdated_date\x18\x04 \x01(\x03R\vupdatedDate\"#\n" +
	"\x11GetAllPairRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x12GetAllPairResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05pairs\x18\x02 \x03(\tR\x05pairsB\tZ\a./protob\x06proto3"

var (
	file_message_balance_component_proto_rawDescOnce sync.Once
	file_message_balance_component_proto_rawDescData []byte
)

func file_message_balance_component_proto_rawDescGZIP() []byte {
	file_message_balance_component_proto_rawDescOnce.Do(func() {
		file_message_balance_component_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_balance_component_proto_rawDesc), len(file_message_balance_component_proto_rawDesc)))
	})
	return file_message_balance_component_proto_rawDescData
}

var file_message_balance_component_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_balance_component_proto_goTypes = []any{
	(*EmitBalanceByUserIdRequest)(nil),  // 0: bs.EmitBalanceByUserIdRequest
	(*EmitBalanceByUserIdResponse)(nil), // 1: bs.EmitBalanceByUserIdResponse
	(*GetBalanceByUserIdRequest)(nil),   // 2: bs.GetBalanceByUserIdRequest
	(*GetBalanceByUserIdResponse)(nil),  // 3: bs.GetBalanceByUserIdResponse
	(*Balance)(nil),                     // 4: bs.Balance
	(*GetAllPairRequest)(nil),           // 5: bs.GetAllPairRequest
	(*GetAllPairResponse)(nil),          // 6: bs.GetAllPairResponse
	(*Error)(nil),                       // 7: error.Error
}
var file_message_balance_component_proto_depIdxs = []int32{
	4, // 0: bs.EmitBalanceByUserIdResponse.balance:type_name -> bs.Balance
	7, // 1: bs.EmitBalanceByUserIdResponse.error:type_name -> error.Error
	4, // 2: bs.GetBalanceByUserIdResponse.user_balance:type_name -> bs.Balance
	7, // 3: bs.GetBalanceByUserIdResponse.error:type_name -> error.Error
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_balance_component_proto_init() }
func file_message_balance_component_proto_init() {
	if File_message_balance_component_proto != nil {
		return
	}
	file_message_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_balance_component_proto_rawDesc), len(file_message_balance_component_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_balance_component_proto_goTypes,
		DependencyIndexes: file_message_balance_component_proto_depIdxs,
		MessageInfos:      file_message_balance_component_proto_msgTypes,
	}.Build()
	File_message_balance_component_proto = out.File
	file_message_balance_component_proto_goTypes = nil
	file_message_balance_component_proto_depIdxs = nil
}
