// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: message/ops_order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNDEFINED OrderStatus = 0
	OrderStatus_ORDER_STATUS_NEW       OrderStatus = 1
	OrderStatus_ORDER_STATUS_ACTIVE    OrderStatus = 2
	OrderStatus_ORDER_STATUS_MATCHED   OrderStatus = 3
	OrderStatus_ORDER_STATUS_DONE      OrderStatus = 4
	OrderStatus_ORDER_STATUS_REMOVED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNDEFINED",
		1: "ORDER_STATUS_NEW",
		2: "ORDER_STATUS_ACTIVE",
		3: "ORDER_STATUS_MATCHED",
		4: "ORDER_STATUS_DONE",
		5: "ORDER_STATUS_REMOVED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNDEFINED": 0,
		"ORDER_STATUS_NEW":       1,
		"ORDER_STATUS_ACTIVE":    2,
		"ORDER_STATUS_MATCHED":   3,
		"ORDER_STATUS_DONE":      4,
		"ORDER_STATUS_REMOVED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_message_ops_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_message_ops_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_message_ops_order_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_ORDER_DIRECTION_UNDEFINED Direction = 0
	Direction_ORDER_DIRECTION_BUY       Direction = 1
	Direction_ORDER_DIRECTION_SELL      Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "ORDER_DIRECTION_UNDEFINED",
		1: "ORDER_DIRECTION_BUY",
		2: "ORDER_DIRECTION_SELL",
	}
	Direction_value = map[string]int32{
		"ORDER_DIRECTION_UNDEFINED": 0,
		"ORDER_DIRECTION_BUY":       1,
		"ORDER_DIRECTION_SELL":      2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_message_ops_order_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_message_ops_order_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_message_ops_order_proto_rawDescGZIP(), []int{1}
}

// Create Order
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pair          string                 `protobuf:"bytes,4,opt,name=pair,proto3" json:"pair,omitempty"`
	InitVolume    float64                `protobuf:"fixed64,5,opt,name=init_volume,json=initVolume,proto3" json:"init_volume,omitempty"`
	InitPrice     float64                `protobuf:"fixed64,6,opt,name=init_price,json=initPrice,proto3" json:"init_price,omitempty"`
	Direction     Direction              `protobuf:"varint,7,opt,name=direction,proto3,enum=ops.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_message_ops_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_ops_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_message_ops_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *CreateOrderRequest) GetInitVolume() float64 {
	if x != nil {
		return x.InitVolume
	}
	return 0
}

func (x *CreateOrderRequest) GetInitPrice() float64 {
	if x != nil {
		return x.InitPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_ORDER_DIRECTION_UNDEFINED
}

// Remove Order
type RemoveOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrderRequest) Reset() {
	*x = RemoveOrderRequest{}
	mi := &file_message_ops_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrderRequest) ProtoMessage() {}

func (x *RemoveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_ops_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrderRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) {
	return file_message_ops_order_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type OrderUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdateEvent) Reset() {
	*x = OrderUpdateEvent{}
	mi := &file_message_ops_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateEvent) ProtoMessage() {}

func (x *OrderUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_message_ops_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateEvent.ProtoReflect.Descriptor instead.
func (*OrderUpdateEvent) Descriptor() ([]byte, []int) {
	return file_message_ops_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderUpdateEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderUpdateEvent) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderUpdateEvent) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pair          string                 `protobuf:"bytes,3,opt,name=pair,proto3" json:"pair,omitempty"`
	InitVolume    float64                `protobuf:"fixed64,4,opt,name=init_volume,json=initVolume,proto3" json:"init_volume,omitempty"`
	FillVolume    float64                `protobuf:"fixed64,5,opt,name=fill_volume,json=fillVolume,proto3" json:"fill_volume,omitempty"`
	InitPrice     float64                `protobuf:"fixed64,6,opt,name=init_price,json=initPrice,proto3" json:"init_price,omitempty"`
	Status        OrderStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=ops.OrderStatus" json:"status,omitempty"`
	Direction     Direction              `protobuf:"varint,8,opt,name=direction,proto3,enum=ops.Direction" json:"direction,omitempty"`
	UpdatedDate   int64                  `protobuf:"varint,9,opt,name=updatedDate,proto3" json:"updatedDate,omitempty"`
	CreatedDate   int64                  `protobuf:"varint,10,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_message_ops_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_message_ops_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_message_ops_order_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Order) GetInitVolume() float64 {
	if x != nil {
		return x.InitVolume
	}
	return 0
}

func (x *Order) GetFillVolume() float64 {
	if x != nil {
		return x.FillVolume
	}
	return 0
}

func (x *Order) GetInitPrice() float64 {
	if x != nil {
		return x.InitPrice
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNDEFINED
}

func (x *Order) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_ORDER_DIRECTION_UNDEFINED
}

func (x *Order) GetUpdatedDate() int64 {
	if x != nil {
		return x.UpdatedDate
	}
	return 0
}

func (x *Order) GetCreatedDate() int64 {
	if x != nil {
		return x.CreatedDate
	}
	return 0
}

var File_message_ops_order_proto protoreflect.FileDescriptor

const file_message_ops_order_proto_rawDesc = "" +
	"\n" +
	"\x17message/ops_order.proto\x12\x03ops\x1a\x13message/error.proto\"\xda\x01\n" +
	"\x12CreateOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04pair\x18\x04 \x01(\tR\x04pair\x12\x1f\n" +
	"\vinit_volume\x18\x05 \x01(\x01R\n" +
	"initVolume\x12\x1d\n" +
	"\n" +
	"init_price\x18\x06 \x01(\x01R\tinitPrice\x12,\n" +
	"\tdirection\x18\a \x01(\x0e2\x0e.ops.DirectionR\tdirection\"?\n" +
	"\x12RemoveOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"h\n" +
	"\x10OrderUpdateEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\x05order\x18\x02 \x01(\v2\n" +
	".ops.OrderR\x05order\x12\"\n" +
	"\x05error\x18\x03 \x01(\v2\f.error.ErrorR\x05error\"\xcc\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04pair\x18\x03 \x01(\tR\x04pair\x12\x1f\n" +
	"\vinit_volume\x18\x04 \x01(\x01R\n" +
	"initVolume\x12\x1f\n" +
	"\vfill_volume\x18\x05 \x01(\x01R\n" +
	"fillVolume\x12\x1d\n" +
	"\n" +
	"init_price\x18\x06 \x01(\x01R\tinitPrice\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.ops.OrderStatusR\x06status\x12,\n" +
	"\tdirection\x18\b \x01(\x0e2\x0e.ops.DirectionR\tdirection\x12 \n" +
	"\vupdatedDate\x18\t \x01(\x03R\vupdatedDate\x12 \n" +
	"\vcreatedDate\x18\n" +
	" \x01(\x03R\vcreatedDate*\xa3\x01\n" +
	"\vOrderStatus\x12\x1a\n" +
	"\x16ORDER_STATUS_UNDEFINED\x10\x00\x12\x14\n" +
	"\x10ORDER_STATUS_NEW\x10\x01\x12\x17\n" +
	"\x13ORDER_STATUS_ACTIVE\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_MATCHED\x10\x03\x12\x15\n" +
	"\x11ORDER_STATUS_DONE\x10\x04\x12\x18\n" +
	"\x14ORDER_STATUS_REMOVED\x10\x05*]\n" +
	"\tDirection\x12\x1d\n" +
	"\x19ORDER_DIRECTION_UNDEFINED\x10\x00\x12\x17\n" +
	"\x13ORDER_DIRECTION_BUY\x10\x01\x12\x18\n" +
	"\x14ORDER_DIRECTION_SELL\x10\x02B\tZ\a./protob\x06proto3"

var (
	file_message_ops_order_proto_rawDescOnce sync.Once
	file_message_ops_order_proto_rawDescData []byte
)

func file_message_ops_order_proto_rawDescGZIP() []byte {
	file_message_ops_order_proto_rawDescOnce.Do(func() {
		file_message_ops_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_ops_order_proto_rawDesc), len(file_message_ops_order_proto_rawDesc)))
	})
	return file_message_ops_order_proto_rawDescData
}

var file_message_ops_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_ops_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_ops_order_proto_goTypes = []any{
	(OrderStatus)(0),           // 0: ops.OrderStatus
	(Direction)(0),             // 1: ops.Direction
	(*CreateOrderRequest)(nil), // 2: ops.CreateOrderRequest
	(*RemoveOrderRequest)(nil), // 3: ops.RemoveOrderRequest
	(*OrderUpdateEvent)(nil),   // 4: ops.OrderUpdateEvent
	(*Order)(nil),              // 5: ops.Order
	(*Error)(nil),              // 6: error.Error
}
var file_message_ops_order_proto_depIdxs = []int32{
	1, // 0: ops.CreateOrderRequest.direction:type_name -> ops.Direction
	5, // 1: ops.OrderUpdateEvent.order:type_name -> ops.Order
	6, // 2: ops.OrderUpdateEvent.error:type_name -> error.Error
	0, // 3: ops.Order.status:type_name -> ops.OrderStatus
	1, // 4: ops.Order.direction:type_name -> ops.Direction
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_ops_order_proto_init() }
func file_message_ops_order_proto_init() {
	if File_message_ops_order_proto != nil {
		return
	}
	file_message_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_ops_order_proto_rawDesc), len(file_message_ops_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_ops_order_proto_goTypes,
		DependencyIndexes: file_message_ops_order_proto_depIdxs,
		EnumInfos:         file_message_ops_order_proto_enumTypes,
		MessageInfos:      file_message_ops_order_proto_msgTypes,
	}.Build()
	File_message_ops_order_proto = out.File
	file_message_ops_order_proto_goTypes = nil
	file_message_ops_order_proto_depIdxs = nil
}
