// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: message/quote_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_ORDER_DIRECTION_UNDEFINED Type = 0
	Type_ORDER_ALL                 Type = 1
	Type_ORDER_SINGLE              Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "ORDER_DIRECTION_UNDEFINED",
		1: "ORDER_ALL",
		2: "ORDER_SINGLE",
	}
	Type_value = map[string]int32{
		"ORDER_DIRECTION_UNDEFINED": 0,
		"ORDER_ALL":                 1,
		"ORDER_SINGLE":              2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_message_quote_manager_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_message_quote_manager_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{0}
}

type GetExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pair          string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Type          Type                   `protobuf:"varint,3,opt,name=type,proto3,enum=qm.Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_message_quote_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_quote_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{0}
}

func (x *GetExchangeRateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetExchangeRateRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *GetExchangeRateRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_ORDER_DIRECTION_UNDEFINED
}

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrdersId      []string               `protobuf:"bytes,3,rep,name=orders_id,json=ordersId,proto3" json:"orders_id,omitempty"`
	Type          Type                   `protobuf:"varint,4,opt,name=type,proto3,enum=qm.Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	mi := &file_message_quote_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_quote_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserOrdersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserOrdersRequest) GetOrdersId() []string {
	if x != nil {
		return x.OrdersId
	}
	return nil
}

func (x *GetUserOrdersRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_ORDER_DIRECTION_UNDEFINED
}

type ExchangeRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Min           string                 `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Average       string                 `protobuf:"bytes,3,opt,name=average,proto3" json:"average,omitempty"`
	Max           string                 `protobuf:"bytes,4,opt,name=max,proto3" json:"max,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=ops.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRate) Reset() {
	*x = ExchangeRate{}
	mi := &file_message_quote_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRate) ProtoMessage() {}

func (x *ExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_message_quote_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRate.ProtoReflect.Descriptor instead.
func (*ExchangeRate) Descriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRate) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *ExchangeRate) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *ExchangeRate) GetAverage() string {
	if x != nil {
		return x.Average
	}
	return ""
}

func (x *ExchangeRate) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

func (x *ExchangeRate) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_ORDER_DIRECTION_UNDEFINED
}

type ExchangeRateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          []*ExchangeRate        `protobuf:"bytes,1,rep,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateList) Reset() {
	*x = ExchangeRateList{}
	mi := &file_message_quote_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateList) ProtoMessage() {}

func (x *ExchangeRateList) ProtoReflect() protoreflect.Message {
	mi := &file_message_quote_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateList.ProtoReflect.Descriptor instead.
func (*ExchangeRateList) Descriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeRateList) GetRate() []*ExchangeRate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type GetExchangeRateResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pairs         map[string]*ExchangeRateList `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *Error                       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateResponse) Reset() {
	*x = GetExchangeRateResponse{}
	mi := &file_message_quote_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateResponse) ProtoMessage() {}

func (x *GetExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_quote_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*GetExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{4}
}

func (x *GetExchangeRateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetExchangeRateResponse) GetPairs() map[string]*ExchangeRateList {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *GetExchangeRateResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetUserOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse) Reset() {
	*x = GetUserOrdersResponse{}
	mi := &file_message_quote_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse) ProtoMessage() {}

func (x *GetUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_quote_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_message_quote_manager_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserOrdersResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_message_quote_manager_proto protoreflect.FileDescriptor

const file_message_quote_manager_proto_rawDesc = "" +
	"\n" +
	"\x1bmessage/quote_manager.proto\x12\x02qm\x1a\x13message/error.proto\x1a\x17message/ops_order.proto\"Z\n" +
	"\x16GetExchangeRateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12\x1c\n" +
	"\x04type\x18\x03 \x01(\x0e2\b.qm.TypeR\x04type\"z\n" +
	"\x14GetUserOrdersRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\torders_id\x18\x03 \x03(\tR\bordersId\x12\x1c\n" +
	"\x04type\x18\x04 \x01(\x0e2\b.qm.TypeR\x04type\"\x8e\x01\n" +
	"\fExchangeRate\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x10\n" +
	"\x03min\x18\x02 \x01(\tR\x03min\x12\x18\n" +
	"\aaverage\x18\x03 \x01(\tR\aaverage\x12\x10\n" +
	"\x03max\x18\x04 \x01(\tR\x03max\x12,\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x0e.ops.DirectionR\tdirection\"8\n" +
	"\x10ExchangeRateList\x12$\n" +
	"\x04rate\x18\x01 \x03(\v2\x10.qm.ExchangeRateR\x04rate\"\xdb\x01\n" +
	"\x17GetExchangeRateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\x05pairs\x18\x02 \x03(\v2&.qm.GetExchangeRateResponse.PairsEntryR\x05pairs\x12\"\n" +
	"\x05error\x18\x03 \x01(\v2\f.error.ErrorR\x05error\x1aN\n" +
	"\n" +
	"PairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.qm.ExchangeRateListR\x05value:\x028\x01\"K\n" +
	"\x15GetUserOrdersResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x06orders\x18\x02 \x03(\v2\n" +
	".ops.OrderR\x06orders*F\n" +
	"\x04Type\x12\x1d\n" +
	"\x19ORDER_DIRECTION_UNDEFINED\x10\x00\x12\r\n" +
	"\tORDER_ALL\x10\x01\x12\x10\n" +
	"\fORDER_SINGLE\x10\x02B\tZ\a./protob\x06proto3"

var (
	file_message_quote_manager_proto_rawDescOnce sync.Once
	file_message_quote_manager_proto_rawDescData []byte
)

func file_message_quote_manager_proto_rawDescGZIP() []byte {
	file_message_quote_manager_proto_rawDescOnce.Do(func() {
		file_message_quote_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_quote_manager_proto_rawDesc), len(file_message_quote_manager_proto_rawDesc)))
	})
	return file_message_quote_manager_proto_rawDescData
}

var file_message_quote_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_quote_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_quote_manager_proto_goTypes = []any{
	(Type)(0),                       // 0: qm.Type
	(*GetExchangeRateRequest)(nil),  // 1: qm.GetExchangeRateRequest
	(*GetUserOrdersRequest)(nil),    // 2: qm.GetUserOrdersRequest
	(*ExchangeRate)(nil),            // 3: qm.ExchangeRate
	(*ExchangeRateList)(nil),        // 4: qm.ExchangeRateList
	(*GetExchangeRateResponse)(nil), // 5: qm.GetExchangeRateResponse
	(*GetUserOrdersResponse)(nil),   // 6: qm.GetUserOrdersResponse
	nil,                             // 7: qm.GetExchangeRateResponse.PairsEntry
	(Direction)(0),                  // 8: ops.Direction
	(*Error)(nil),                   // 9: error.Error
	(*Order)(nil),                   // 10: ops.Order
}
var file_message_quote_manager_proto_depIdxs = []int32{
	0,  // 0: qm.GetExchangeRateRequest.type:type_name -> qm.Type
	0,  // 1: qm.GetUserOrdersRequest.type:type_name -> qm.Type
	8,  // 2: qm.ExchangeRate.direction:type_name -> ops.Direction
	3,  // 3: qm.ExchangeRateList.rate:type_name -> qm.ExchangeRate
	7,  // 4: qm.GetExchangeRateResponse.pairs:type_name -> qm.GetExchangeRateResponse.PairsEntry
	9,  // 5: qm.GetExchangeRateResponse.error:type_name -> error.Error
	10, // 6: qm.GetUserOrdersResponse.orders:type_name -> ops.Order
	4,  // 7: qm.GetExchangeRateResponse.PairsEntry.value:type_name -> qm.ExchangeRateList
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_message_quote_manager_proto_init() }
func file_message_quote_manager_proto_init() {
	if File_message_quote_manager_proto != nil {
		return
	}
	file_message_error_proto_init()
	file_message_ops_order_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_quote_manager_proto_rawDesc), len(file_message_quote_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_quote_manager_proto_goTypes,
		DependencyIndexes: file_message_quote_manager_proto_depIdxs,
		EnumInfos:         file_message_quote_manager_proto_enumTypes,
		MessageInfos:      file_message_quote_manager_proto_msgTypes,
	}.Build()
	File_message_quote_manager_proto = out.File
	file_message_quote_manager_proto_goTypes = nil
	file_message_quote_manager_proto_depIdxs = nil
}
